apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-carmen
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: team-carmen
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: git@github.com:CarmenAPuccio/GeoLocationAPI.git
    path: templates
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true