apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-burnham-workload
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: team-burnham
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://github.com/kcoleman731/argo-apps
    path: team-burnham
    targetRevision: {{ .Values.spec.source.targetRevision }}
